<div align="center">
  <a href="https://github.com/JuJubali" target="_blank" rel="external">
  <img height="180em" src="https://github-readme-stats.vercel.app/api?username=JuJubali&show_icons=false&theme=moltack&include_all_commits=false&count_private=false"/>
  <img height="180em" src="https://github-readme-stats.vercel.app/api/top-langs/?username=JuJubali&layout=compact&langs_count=7&theme=moltack"/>
<img align="right" alt="Juliaa-pic" height="150" style="border-radius:50px;" src="https://media.discordapp.net/attachments/623523047588233218/935341447387971584/20220124_221052.gif">
</div>
<div>
   ![Snake animation](https://github.com/Jujubali/Readme/blob/output/github-contribution-grid-snake.svg)
  </div>
